FROM ubuntu:24.04 as builder

RUN apt-get update && apt-get install -y \
    build-essential \
    dos2unix \
    git \
    libcurl4-openssl-dev

# Set working directory
WORKDIR /app

COPY ./src /app

RUN dos2unix /app/mkreadme

RUN make

EXPOSE 6669

CMD ["./gate"]
